name: Build_Test

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Windows
    runs-on: windows-2022


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Prepare
        run: mkdir -p ./artifacts
      - name: Build solution
        run: dotnet publish --sc true -o artifacts /p:PublishSingleFile=true .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: steam-windows
          path: artifacts/ 
